exports = class PlayerModel {
    constructor() {
        // Initialize the data
        this.name = undefined;
        this.age = 18;
        this.sex = 0;
        this.firstHeadShape = 0;
        this.secondHeadShape = 0;
        this.firstSkinTone = 0;
        this.secondSkinTone = 0;
        this.headMix = 0.5;
        this.skinMix = 0.5;
        this.hairModel = 0;
        this.firstHairColor = 0;
        this.secondHairColor = 0;
        this.beardModel = 255;
        this.beardColor = 0;
        this.chestModel = 255;
        this.chestColor = 0;
        this.blemishesModel = 255;
        this.ageingModel = 255;
        this.complexionModel = 255;
        this.sundamageModel = 255;
        this.frecklesModel = 255;
        this.eyesColor = 0;
        this.eyebrowsModel = 255;
        this.eyebrowsColor = 0;
        this.makeupModel = 255;
        this.blushModel = 255;
        this.blushColor = 0;
        this.lipstickModel = 255;
        this.lipstickColor = 0;
        this.noseWidth = 0.0;
        this.noseHeight = 0.0;
        this.noseLength = 0.0;
        this.noseBridge = 0.0;
        this.noseTip = 0.0;
        this.noseShift = 0.0;
        this.browHeight = 0.0;
        this.browWidth = 0.0;
        this.cheekboneHeight = 0.0;
        this.cheekboneWidth = 0.0;
        this.eyes = 0.0;
        this.lips = 0.0;
        this.jawWidth = 0.0;
        this.jawHeight = 0.0;
        this.chinLength = 0.0;
        this.chinPosition = 0.0;
        this.chinWidth = 0.0;
        this.chinShape = 0.0;
        this.neckWidth = 0.0;
        this.noseWidth = 0.0;
    }    
}